INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-01', 'Breaking news1', 'Mind-blowing news1', 'text1');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-02', 'Breaking news1', 'Mind-blowing news2', 'text2');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-03', 'Breaking news1', 'Mind-blowing news3', 'text3');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-04', 'Breaking news1', 'Mind-blowing news4', 'text4');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-05', 'Breaking news1', 'Mind-blowing news5', 'text5');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'atext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'atext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'btext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'btext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'ctext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'ctext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'dtext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'dtext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'ftext6');
INSERT INTO ARTICLE (PUBLISHED_DATE, TITLE, SHORT_DESCRIPTION, ARTICLE_TEXT) VALUES ('2017-01-06', 'Breaking news1', 'Mind-blowing news6', 'gtext6');

